# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with flake8, isort and possibly run tests

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install flake8 isort pytest
          pip install -r requirements.txt
      - name: ls
        run: |
          ls -la
      #- name: Lint with flake8
       # run: |
        #  flake8 .
      - name: isort
        run: |
          isort --check .
      - name: Test with pytest
        run: |
          pytest
