# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with flake8, isort and possibly run tests
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          echo "install flake8 isort pytest"
          pip install flake8 isort pytest
          echo "Done: install flake8 isort pytest"
          echo "install from requirements"
          pip install -r requirements.txt
          echo "Done: install from requirements"
          echo "testing ls"
          ls -la
          echo "Done: ls"
          echo "testing flack8"
          flake8 .  --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          echo "Done: testing flack8"
          echo "testing pytest"
          pytest tests
          echo "Done: testing pytest"
